/**
 * npm run panels
 *
 * Writes src/assets/panels/SLOTS.md — a checklist of every picture slot on the
 * site, marked ✅ when a matching image is in the folder — and refreshes
 * credits.schema.json so VS Code autocompletes slot names in credits.json.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { listSlots } from '../src/data/slots';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, '../src/assets/panels');
const IMAGE = /\.(jpe?g|png|webp|avif|gif)$/i;

const files = readdirSync(dir).filter((f) => IMAGE.test(f));
const byKey = new Map(files.map((f) => [f.replace(/\.[^.]+$/, '').toLowerCase(), f]));
const slots = listSlots();
const keys = new Set(slots.map((s) => s.key));

const filled = slots.filter((s) => byKey.has(s.key)).length;
const unknown = files.filter((f) => !keys.has(f.replace(/\.[^.]+$/, '').toLowerCase()));

const lines: string[] = [
  '# Image slots',
  '',
  '<!-- Generated by `npm run panels`. Do not edit by hand. -->',
  '',
  `**${filled} of ${slots.length} slots filled.** Put a picture in this folder named exactly as the *File name* column`,
  '(any of .jpg .jpeg .png .webp .avif), then reload the site. Run `npm run panels` again to update this list.',
  '',
  'Only add images you own or have permission to publish. See README.md in this folder.',
  '',
];

if (unknown.length) {
  lines.push('## ⚠️ Files that match no slot', '', 'Check the spelling — these images are not shown anywhere:', '');
  for (const f of unknown) lines.push(`- \`${f}\``);
  lines.push('');
}

const sections = [...new Set(slots.map((s) => s.section))];
for (const section of sections) {
  const rows = slots.filter((s) => s.section === section);
  const done = rows.filter((s) => byKey.has(s.key)).length;
  lines.push(`## ${section} — ${done}/${rows.length}`, '', '| | File name | Where it appears | Shape | Page |', '|---|---|---|---|---|');
  for (const s of rows) {
    const f = byKey.get(s.key);
    lines.push(`| ${f ? '✅' : '⬜'} | \`${f ?? `${s.key}.jpg`}\` | ${s.where.replace(/\|/g, '/')} | ${s.shape} | \`${s.page}\` |`);
  }
  lines.push('');
}

writeFileSync(join(dir, 'SLOTS.md'), lines.join('\n'));

const schema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Panel image credits',
  type: 'object',
  properties: {
    $schema: { type: 'string' },
    _help: { type: 'string' },
    credits: {
      type: 'object',
      description: 'Key = image file name without extension.',
      propertyNames: { enum: [...keys] },
      additionalProperties: {
        type: 'object',
        additionalProperties: false,
        properties: {
          alt: { type: 'string', description: 'What the picture shows (for screen readers).' },
          credit: { type: 'string', description: 'Artist / owner, e.g. "Fan art by @name".' },
          license: { type: 'string', description: 'e.g. "Used with permission", "CC BY 4.0", "Own work".' },
          sourceUrl: { type: 'string', description: 'Where the picture came from.' },
        },
      },
    },
  },
};
writeFileSync(join(dir, 'credits.schema.json'), JSON.stringify(schema, null, 2) + '\n');

console.log(`Image slots: ${filled}/${slots.length} filled → src/assets/panels/SLOTS.md`);
if (unknown.length) console.log(`⚠  ${unknown.length} file(s) match no slot: ${unknown.join(', ')}`);
